### ISSUE TITLE
controller.h not found

### ISSUE THREAD

**Issue by manouhihalid** [Gustbel/ble-beacons-scanner_esp-idf#1]
Hi,

 i am triying to use this example but i get error when compile.

controller.h not found and also 
esp_gap_ble_api.h
esp_gattc_api.h
esp_gatt_defs.h
esp_bt_main.h

thanks for your help

**Comment by Gustbel** [comment]
Hi, @manouhihalid 
Please note that this repo is optimized for **version v4.1** of _esp-idf_

you can install the version with: 
In Linux:
```
sudo apt update
sudo apt install git wget flex bison gperf python python-pip python-setuptools cmake ninja-build ccache libffi-dev libssl-dev
git clone -b v4.1 --recursive https://github.com/espressif/esp-idf.git
```

In Windows:
https://dl.espressif.com/dl/esp-idf-tools-setup-2.3.exe

Tell me later if you were able to solve it with this.

**Comment by manouhihalid** [comment]
Thanks
it'is now OK
